[package]
name = "life2"
authors = ["Bart Massey <bart.massey@gmail.com>"]
edition = "2021"
version = "0.1.0"

[dependencies]
cortex-m-rt = "0.7.5"
panic-probe = "1.0.0"
embassy-futures = "0.1.2"

[dependencies.defmt-rtt]
version = "1.1.0"
optional = true

[dependencies.microbit-bsp]
version = "0.5.0"
default-features = false
git = "https://github.com/BartMassey-upstream/microbit-bsp"
branch = "upgrade-20260103"

[dependencies.nanorand]
version = "0.8.0"
default-features = false
features = ["pcg64"]

[dependencies.embassy-executor]
version = "0.9.1"
features = ["arch-cortex-m", "executor-thread"]

[dependencies.cortex-m]
version = "0.7.7"
features = ["critical-section-single-core"]


[profile.release]
debug = 2

[features]
backlight = []
defmt = [
      "dep:defmt-rtt",
      "embassy-futures/defmt",
      "embassy-executor/defmt",
      "panic-probe/print-defmt",
      "microbit-bsp/defmt",
]
