[package]
name = "life2"
authors = ["Bart Massey <bart.massey@gmail.com>"]
edition = "2021"
version = "0.1.0"

[dependencies]
defmt = "1.0.1"
defmt-rtt = "1.1.0"
cortex-m-rt = "0.7.5"
embassy-futures = { version = "0.1.2", features = ["defmt"] }
nanorand = { version = "0.8.0", default-features = false, features = ["pcg64"] }

[dependencies.microbit-bsp]
path = "/local/src/old/microbit-bsp"

[dependencies.embassy-executor]
version = "0.9.1"
features = ["defmt", "arch-cortex-m", "executor-thread"]

[dependencies.cortex-m]
version = "0.7.7"
features = ["critical-section-single-core"]

[dependencies.panic-probe]
version = "1.0.0"
features = ["print-defmt"]

[profile.release]
debug = 2

[features]
backlight = []
