[build]
target = "thumbv7em-none-eabihf"

[target.thumbv7em-none-eabihf]
runner = "probe-rs run --protocol=swd"
rustflags = [
  "-C", "linker=flip-link",
  "-C", "link-arg=-Tlink.x",
]

[env]
DEFMT_LOG = "trace"
